apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-secret
stringData:
  # For AWS set it to "https://s3.<region>.amazonaws.com"
  endpoint: https://s3.eu-west-1.amazonaws.com
  # If not on S3, set it to ""
  region: eu-west-1
